apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
spec:
  containers:
  - image: mysql
    name: mysql
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "B4teau123!"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
