apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rbac-pod
  name: rbac-pod
spec:
  containers:
  - image: bitnami/kubectl:latest
    name: rbac-pod
    command: ['sleep', '3600']
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
