apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
spec:
  containers:
  - image: mysql
    name: mysql
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: password
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: password
      - name: MYSQL_DATABASE
        valueFrom:
          configMapKeyRef:
            name: mysql
            key: database
      - name: MYSQL_USER
        valueFrom:
          configMapKeyRef:
            name: mysql
            key: user
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
