apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: flask
  name: flask
spec:
  containers:
  - image: harbor.kakor.ovh/public/flask-default:latest
    name: flask
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
