apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-nfs
  name: nginx-nfs
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx-nfs
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - MKNOD
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nfs
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfs-pvc