apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"pv-correction"},"spec":{"accessModes":["ReadWriteMany"],"capacity":{"storage":"1Gi"},"mountOptions":["nfsvers=3"],"nfs":{"path":"/Volume1/public/nfs-share-openshift/correction","server":"192.168.1.56"},"persistentVolumeReclaimPolicy":"Recycle","storageClassName":"nfs-correction","volumeMode":"Filesystem"}}
  creationTimestamp: "2025-01-31T12:34:35Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pv-correction
  resourceVersion: "1075812"
  uid: f98c8554-2d98-4480-bf08-ed97b5e8effc
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  mountOptions:
  - nfsvers=3
  nfs:
    path: /Volume1/public/nfs-share-openshift/correction
    server: 192.168.1.56
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-correction
  volumeMode: Filesystem
status:
  phase: Available