apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstack-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-correction
  nfs:
    path: /Volume1/public/nfs-share-openshift/correction
    server: 192.168.1.56